// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo81Eg_expEeXNNfxGmmzCPvyiPkC9zUE',
    appId: '1:631866590246:web:24e03c84fab2a328f592e7',
    messagingSenderId: '631866590246',
    projectId: 'whatsapclone-1d478',
    authDomain: 'whatsapclone-1d478.firebaseapp.com',
    storageBucket: 'whatsapclone-1d478.appspot.com',
    measurementId: 'G-1QVEQZTFTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHOSrrerqwjHYerJiBjP_zi-f5o6MaTM',
    appId: '1:631866590246:android:860da4f52f5d611ef592e7',
    messagingSenderId: '631866590246',
    projectId: 'whatsapclone-1d478',
    storageBucket: 'whatsapclone-1d478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztDS2Ab9B__wsRz4eDm9tXS2_LNlMY78',
    appId: '1:631866590246:ios:b1182e0685eee895f592e7',
    messagingSenderId: '631866590246',
    projectId: 'whatsapclone-1d478',
    storageBucket: 'whatsapclone-1d478.appspot.com',
    androidClientId: '631866590246-nfl6otma5s4kod3p11hmkq1d75qf4eki.apps.googleusercontent.com',
    iosClientId: '631866590246-ea1jpu0leq3f0fgnf0otobfpdvnpbiun.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCztDS2Ab9B__wsRz4eDm9tXS2_LNlMY78',
    appId: '1:631866590246:ios:b1182e0685eee895f592e7',
    messagingSenderId: '631866590246',
    projectId: 'whatsapclone-1d478',
    storageBucket: 'whatsapclone-1d478.appspot.com',
    androidClientId: '631866590246-nfl6otma5s4kod3p11hmkq1d75qf4eki.apps.googleusercontent.com',
    iosClientId: '631866590246-ea1jpu0leq3f0fgnf0otobfpdvnpbiun.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbloc',
  );
}
